repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ocamlformat
        name: ocamlformat
        entry: ocamlformat --inplace
        language: system
        files: \.ml$|\.mli$

  - repo: local
    hooks:
      - id: dune-build
        name: dune build
        entry: dune build
        language: system
        files: \.ml$|\.mli$|dune-project$|dune$
        pass_filenames: false
      - id: dune-test
        name: dune test
        entry: dune runtest
        language: system
        files: \.ml$|\.mli$|dune-project$|dune$
        pass_filenames: false
